/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */ export var styles = ['input.ng-valid[_ngcontent-%COMP%] {\r\n    border-left-style: solid;\r\n    border-left-color: forestgreen;\r\n    border-left-width: 5px;\r\n}\r\n\r\ninput.ng-invalid[_ngcontent-%COMP%] {\r\n    border-left-style: solid;\r\n    border-left-color: hotpink;\r\n    border-left-width: 5px;\r\n}'];
